# Generated by Django 6.0.7 on 2026-08-04 05:39

import apps.candidates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('linkedin_url', models.CharField(max_length=300)),
                ('upload_cv', models.FileField(blank=True, null=True, upload_to='resume/', validators=[apps.candidates.models.validate_resume_file], verbose_name='Resume/cv')),
                ('picture', models.ImageField(blank=True, default='profile_pcs/default.jpg', null=True, upload_to='profile/')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canidates_profile', to='accounts.account')),
            ],
        ),
    ]
